import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 35,
    //justifyContent: 'space-between',
  },
  imageContainer: {
    flex: 1,
    //alignItems: 'flex-start',
    marginVertical: 78,
    //paddingRight: 0,
    //paddingHorizontal: 35,
    //maxHeight: '50%',
  },
  textContainer: {
    flex: 1,
    //width:'100%',
    //maxHeight: '50%',
  },
  UpperTextContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    //paddingTop: 42,
  },
  LowerTextContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    marginBottom: 30,
  },
  title: {
    fontFamily: 'Alice',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 34,
    lineHeight: 34,
    textAlign: 'left',
    letterSpacing: -0.408,
    color: '#240E54',
    marginTop: 60,
  },
  subtitle: {
    fontFamily: 'Alice',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 20,
    lineHeight: 29,
    textAlign: 'left',
    letterSpacing: -0.408,
    color: '#240E54',
    marginVertical: 22,
  },
  text: {
    fontFamily: 'Alice',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 20,
    lineHeight: 29,
    textAlign: 'left',
    letterSpacing: -0.408,
    color: '#240E54',
    },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 35,
    marginBottom: 70,
  },
  button: {
    width: 159,
    height: 52,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#240E54',
    borderRadius: 48,
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: '4%',
  },
  buttonText: {
    //fontFamily: 'SF Pro text',
    fontSize: 18,
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 18,
    lineHeight: 20,
    textAlign: 'center',
  },
  skipButton: {
    backgroundColor: '#FFFFFF',
  },
  skipButtonText: {
    color: '#240E54',
  },
  nextButton: {
    backgroundColor: '#240E54',
  },
  nextButtonText: {
    color: '#FFFFFF',
  },
});
